require('plugs.theme-conf')
require('plugs.nvim-cmp-conf')
require('plugs.nvim-lsp-conf')
require('plugs.lualine-conf')
require('plugs.comment-conf')
-- require('plugs.formatter-conf')
require('plugs.conform-conf')
require('plugs.nvim-treesitter-conf')
require('plugs.nvim-tree-conf')
require('plugs.telescope-conf')
require('plugs.nvim-autopairs-conf')
